/**
 * Local file storage port + helpers.
 *
 * The application depends on {@link IFileStorage} rather than `node:fs`
 * directly, so the storage backend (local disk now, cloud later) can be swapped
 * without touching callers. This module contains no business rules — it is pure
 * byte I/O plus a deterministic naming/organisation strategy.
 */

/** Metadata describing a stored file. */
export interface StoredFile {
  /** Storage-relative key, e.g. `images/ab/abcd1234.png`. */
  readonly key: string;
  /** Size in bytes. */
  readonly size: number;
  /** Detected/declared content type, if known. */
  readonly contentType: string | null;
  /** ISO timestamp the file was written. */
  readonly createdAt: string;
}

/** Options accepted when saving a blob. */
export interface SaveOptions {
  readonly contentType?: string;
  /** Preferred file extension (without dot), used by the naming strategy. */
  readonly extension?: string;
}

/** Provider-agnostic local file storage contract. */
export interface IFileStorage {
  /** Persist bytes and return a handle. The key is generated by the backend. */
  save(data: Uint8Array, options?: SaveOptions): Promise<StoredFile>;
  /** Persist bytes under an explicit, caller-chosen key. */
  saveAs(key: string, data: Uint8Array, options?: SaveOptions): Promise<StoredFile>;
  /** Read bytes back for a key. Rejects with StorageError if missing. */
  read(key: string): Promise<Uint8Array>;
  /** Whether a key exists. */
  exists(key: string): Promise<boolean>;
  /** Delete a key. No-op (resolves) if it does not exist. */
  delete(key: string): Promise<void>;
  /** List all keys, optionally restricted to a key prefix. */
  list(prefix?: string): Promise<readonly string[]>;
  /** Resolve a storage key to an absolute filesystem path. */
  resolvePath(key: string): string;
}

/** Map a handful of common image extensions to their MIME content types. */
export const CONTENT_TYPE_BY_EXTENSION: Readonly<Record<string, string>> = {
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  webp: 'image/webp',
  gif: 'image/gif',
  avif: 'image/avif',
  bmp: 'image/bmp',
};

/** Infer a content type from a file extension (without the dot). */
export const contentTypeForExtension = (extension: string | undefined): string | null => {
  if (extension === undefined) {
    return null;
  }
  return CONTENT_TYPE_BY_EXTENSION[extension.toLowerCase()] ?? null;
};

/**
 * Sharded naming strategy: a content-addressable-ish key that fans files out
 * across two-character subdirectories to avoid huge flat folders. The first two
 * characters of the id form the shard directory.
 */
export const buildStorageKey = (
  namespace: string,
  id: string,
  extension: string | undefined,
): string => {
  const safeId = id.replace(/[^a-zA-Z0-9_-]/g, '');
  const shard = (safeId.slice(0, 2) || '00').toLowerCase();
  const ext = extension !== undefined && extension.length > 0 ? `.${extension.replace(/^\./, '')}` : '';
  return `${namespace}/${shard}/${safeId}${ext}`;
};
